# This initialize the number of drones
# Should be at the top
nb_drones: 5

# This is where every drone starts
# Expected syntax:
# start_hub: name x y [metadata]
# start_hub: name x y [metadata]
start_hub: start 0 0

# This is where every drone should end
# Expected syntax:
# end_hub: name x y [metadata]
end_hub: end 4 0

# You can add other hub
# Expected syntax:
# hub: name x y [metadata]
hub: hub1 1 0 [zone=restricted max_drones=2]
hub: hub2 2 0 [max_drones=3]
hub: hub3 3 0 [color=blue]

# To link the hub, we use connection:
# Expected syntax:
# connection: <hubname>-<hubname> [metadata]
connection: start-hub1 [max_link_capacity=2]
connection: hub1-hub2
connection: hub2-hub3
connection: hub3-end
