nb_drones: 10

start_hub: start 0 0
hub: case1 1 0 [max_drones=4]
hub: case2 1 1 [max_drones=4]
hub: intersection 2 0 [max_drones=2 zone=restricted]
end_hub: end 3 0

connection: start-case1
connection: start-case2
connection: case1-intersection
connection: case2-intersection
connection: intersection-end
